name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**.yml"
      - ".rusty-hook.toml"
      - "**/Makefile.toml"
      - "**.py"
      - "README.md"
  workflow_run:
    workflows: ["Generate This Week in Rust"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: npm i && npx tailwindcss -i ./input.css -o ./out/blog/output.css && RUST_BACKTRACE=1 cargo run --release
      - name: Generate Previews
        run: |
          cd preview_generator
          cargo run --release -- blog ../articles ../out/blog/articles
          cargo run --release -- this_week ../esta_semana_en_rust/ ../out/blog/articles

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./out/blog

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./artifact --project-name=blog
