name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/**.yml"
      - ".rusty-hook.toml"
      - "**/Makefile.toml"
      - "**.py"
      - "README.md"
  workflow_run:
    workflows: ["Generate This Week in Rust"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: npm i && npx tailwindcss -i ./input.css -o ./out/output.css && RUST_BACKTRACE=1 cargo run --release
      - name: Generate Previews
        run: |
          cd preview_generator
          cargo run --release -- blog ../articles ../out/articles
          cargo run --release -- this_week ../esta_semana_en_rust/ ../out/articles/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: out
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: out
