name: Quality Gate
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - ".rusty-hook.toml"
      - ".github/workflows/**.yml"
      - "**/Makefile.toml"
      - "**.py"
      - "README.md"

jobs:
  quality-gate:
    uses: RustLangES/workflows/.github/workflows/quality-gate-front.yml@main
